import { BadRequestException, Injectable } from '@nestjs/common'; import { PrismaService } from '../../core/prisma/prisma.service'; import { FiscalProviderFactory } from './providers/provider.factory'; import crypto from 'crypto';
@Injectable() export class FiscalisationService {constructor(private prisma:PrismaService,private factory:FiscalProviderFactory){}
async listDevices(companyId:string){return this.prisma.fiscalDevice.findMany({where:{branch:{companyId}},include:{branch:true,fiscalDays:{orderBy:{dayNo:'desc'},take:3}}})}
async register(companyId:string,deviceId:string){const d=await this.prisma.fiscalDevice.findFirst({where:{id:deviceId,branch:{companyId}},include:{branch:{include:{company:true}}}}); if(!d) throw new BadRequestException('Device not found'); const p=this.factory.get(); const verified=await p.verifyTaxpayer({tin:d.branch.company.tin,vatNumber:d.branch.company.vatNumber}); const res=await p.registerDevice({serialNumber:d.serialNumber,company:verified}); await this.prisma.fiscalIntegrationLog.create({data:{deviceId:d.id,operation:'registerDevice',status:'OK',request:{serialNumber:d.serialNumber},response:res}}); return this.prisma.fiscalDevice.update({where:{id:d.id},data:{status:'ACTIVE',zimraDeviceId:res.zimraDeviceId,certificateRef:res.certificateRef,certificateExpiresAt:new Date(res.expiresAt)}})}
async openDay(companyId:string,deviceId:string){const d=await this.prisma.fiscalDevice.findFirst({where:{id:deviceId,branch:{companyId}}}); if(!d) throw new BadRequestException('Device not found'); if(d.status!=='ACTIVE') throw new BadRequestException('Register device first'); if(d.dayStatus==='OPEN') throw new BadRequestException('Fiscal day already open'); const dayNo=d.fiscalDayNo+1; const res=await this.factory.get().openDay({deviceId:d.zimraDeviceId,dayNo}); return this.prisma.$transaction(async tx=>{await tx.fiscalIntegrationLog.create({data:{deviceId:d.id,operation:'openDay',status:'OK',response:res}}); await tx.fiscalDay.create({data:{deviceId:d.id,dayNo,status:'OPEN',openedAt:new Date()}}); return tx.fiscalDevice.update({where:{id:d.id},data:{fiscalDayNo:dayNo,receiptCounter:0,dayStatus:'OPEN'}})})}
async fiscalise(companyId:string,deviceId:string,invoiceId:string){const inv=await this.prisma.salesInvoice.findFirst({where:{id:invoiceId,companyId},include:{lines:true,customer:true,fiscalReceipt:true}}); if(!inv) throw new BadRequestException('Invoice not found'); if(inv.status==='DRAFT') throw new BadRequestException('Post invoice before fiscalisation'); if(!inv.fiscalRequired) throw new BadRequestException('Invoice does not require fiscalisation'); if(inv.fiscalReceipt) throw new BadRequestException('Invoice already has fiscal receipt');
const d=await this.prisma.fiscalDevice.findFirst({where:{id:deviceId,branch:{companyId}}}); if(!d||d.dayStatus!=='OPEN') throw new BadRequestException('Fiscal day is not open');
const allocated=await this.prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{id:string;"fiscalDayNo":number;"receiptCounter":number;"globalReceiptNo":number}>>`UPDATE "FiscalDevice" SET "receiptCounter" = "receiptCounter" + 1, "globalReceiptNo" = "globalReceiptNo" + 1 WHERE id = ${deviceId} AND "dayStatus" = 'OPEN' RETURNING id, "fiscalDayNo", "receiptCounter", "globalReceiptNo"`; if(!rows[0]) throw new BadRequestException('Unable to allocate receipt sequence'); return rows[0]});
const payload={deviceID:d.zimraDeviceId,fiscalDayNo:allocated.fiscalDayNo,receiptCounter:allocated.receiptCounter,globalReceiptNo:allocated.globalReceiptNo,receiptType:'FiscalInvoice',invoiceNo:inv.invoiceNo,currency:inv.currency,total:Number(inv.total),tax:Number(inv.taxTotal),lines:inv.lines.map(l=>({name:l.description,qty:Number(l.quantity),unitPrice:Number(l.unitPrice),taxRate:Number(l.taxRate),taxAmount:Number(l.taxAmount),total:Number(l.lineTotal),hsCode:l.hsCode}))}; const hash=crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');
const receipt=await this.prisma.fiscalReceipt.create({data:{deviceId:d.id,invoiceId:inv.id,fiscalDayNo:allocated.fiscalDayNo,receiptCounter:allocated.receiptCounter,globalReceiptNo:allocated.globalReceiptNo,receiptHash:hash,rawRequest:payload,status:'PENDING'}}); try{const res=await this.factory.get().submitReceipt({...payload,receiptHash:hash}); await this.prisma.$transaction(async tx=>{await tx.fiscalReceipt.update({where:{id:receipt.id},data:{status:'FISCALISED',zimraReceiptId:res.receiptID,serverSignature:res.receiptServerSignature,rawResponse:res,submittedAt:new Date()}}); await tx.salesInvoice.update({where:{id:inv.id},data:{fiscalStatus:'FISCALISED'}}); await tx.fiscalDay.update({where:{deviceId_dayNo:{deviceId:d.id,dayNo:allocated.fiscalDayNo}},data:{receiptCount:{increment:1},grossTotal:{increment:inv.total},taxTotal:{increment:inv.taxTotal}}}); await tx.fiscalIntegrationLog.create({data:{deviceId:d.id,operation:'submitReceipt',status:'OK',request:payload,response:res}})}); return this.prisma.fiscalReceipt.findUnique({where:{id:receipt.id}})}catch(e:any){await this.prisma.fiscalReceipt.update({where:{id:receipt.id},data:{status:'RETRY',rawResponse:{error:e.message}}}); await this.prisma.salesInvoice.update({where:{id:inv.id},data:{fiscalStatus:'RETRY'}}); throw e}}
async closeDay(companyId:string,deviceId:string){const d=await this.prisma.fiscalDevice.findFirst({where:{id:deviceId,branch:{companyId}}}); if(!d||d.dayStatus!=='OPEN') throw new BadRequestException('No open fiscal day'); const day=await this.prisma.fiscalDay.findUnique({where:{deviceId_dayNo:{deviceId:d.id,dayNo:d.fiscalDayNo}}}); const res=await this.factory.get().closeDay({deviceId:d.zimraDeviceId,dayNo:d.fiscalDayNo,receiptCount:day?.receiptCount,grossTotal:Number(day?.grossTotal||0),taxTotal:Number(day?.taxTotal||0)}); return this.prisma.$transaction(async tx=>{await tx.fiscalDay.update({where:{deviceId_dayNo:{deviceId:d.id,dayNo:d.fiscalDayNo}},data:{status:'CLOSED',closedAt:new Date()}}); await tx.fiscalIntegrationLog.create({data:{deviceId:d.id,operation:'closeDay',status:'OK',response:res}}); return tx.fiscalDevice.update({where:{id:d.id},data:{dayStatus:'CLOSED'}})})}
async receipts(companyId:string){return this.prisma.fiscalReceipt.findMany({where:{invoice:{companyId}},include:{invoice:true,device:{include:{branch:true}}},orderBy:{createdAt:'desc'}})} }
