'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth-store';
import { Button, Card, Form, Input, Modal, Select, Table, Typography, message } from 'antd';
import { PlusOutlined } from '@ant-design/icons';

export default function Platform(){
  const router=useRouter(),s=useAuth(),qc=useQueryClient(); const [open,setOpen]=useState(false); const [form]=Form.useForm();
  useEffect(()=>{if(!s.token)router.replace('/login');else if(!s.user?.isPlatformAdmin)router.replace('/dashboard')},[s.token,s.user,router]);
  const q=useQuery({queryKey:['tenants'],queryFn:()=>api('/platform/tenants'),enabled:!!s.token&&!!s.user?.isPlatformAdmin});
  const plans=useQuery({queryKey:['plans'],queryFn:()=>api('/platform/plans'),enabled:!!s.token&&!!s.user?.isPlatformAdmin});
  async function create(v:any){try{await api('/platform/tenants',{method:'POST',body:JSON.stringify(v)});message.success('Tenant created');setOpen(false);form.resetFields();qc.invalidateQueries({queryKey:['tenants']})}catch(e:any){message.error(e.message)}}
  return <main className="min-h-screen p-8 bg-slate-950 text-white"><div className="max-w-7xl mx-auto"><div className="flex justify-between items-center mb-8"><div><Typography.Title style={{color:'white',marginBottom:4}}>NexusERP Platform Admin</Typography.Title><div className="text-slate-400">Subscribers, companies and commercial plans.</div></div><div className="flex gap-2"><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>Onboard Tenant</Button><Button onClick={()=>{s.logout();router.push('/login')}}>Sign out</Button></div></div><Card className="border-0"><Table rowKey="id" loading={q.isLoading} dataSource={q.data||[]} columns={[{title:'Tenant',dataIndex:'name'},{title:'Slug',dataIndex:'slug'},{title:'Companies',dataIndex:'companies',render:(v:any[])=>v.length},{title:'Plan',dataIndex:['subscription','plan','name']},{title:'Status',dataIndex:['subscription','status']}]} /></Card></div><Modal width={760} open={open} onCancel={()=>setOpen(false)} footer={null} title="Onboard new subscriber"><Form form={form} layout="vertical" onFinish={create} initialValues={{planName:'Professional',baseCurrency:'USD',branchName:'Main Branch',branchCode:'MAIN'}}><div className="grid md:grid-cols-2 gap-x-4"><Form.Item label="Tenant / Group Name" name="tenantName" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Slug" name="slug" rules={[{required:true}]}><Input placeholder="acme-holdings"/></Form.Item><Form.Item label="Plan" name="planName" rules={[{required:true}]}><Select options={(plans.data||[]).map((p:any)=>({label:`${p.name} — $${p.monthlyPrice}/month`,value:p.name}))}/></Form.Item><Form.Item label="Legal Company Name" name="legalName" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Trading Name" name="tradingName"><Input/></Form.Item><Form.Item label="Company Code" name="companyCode" rules={[{required:true}]}><Input placeholder="ACME"/></Form.Item><Form.Item label="TIN" name="tin"><Input/></Form.Item><Form.Item label="VAT Number" name="vatNumber"><Input/></Form.Item><Form.Item label="Base Currency" name="baseCurrency"><Input/></Form.Item><Form.Item label="Branch Name" name="branchName" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Branch Code" name="branchCode" rules={[{required:true}]}><Input/></Form.Item><div/></div><Typography.Title level={5}>Initial Company Administrator</Typography.Title><div className="grid md:grid-cols-2 gap-x-4"><Form.Item label="First Name" name="adminFirstName" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Last Name" name="adminLastName" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="Email" name="adminEmail" rules={[{required:true,type:'email'}]}><Input/></Form.Item><Form.Item label="Temporary Password" name="adminPassword" rules={[{required:true,min:10}]}><Input.Password/></Form.Item></div><Button type="primary" htmlType="submit" block size="large">Create Tenant</Button></Form></Modal></main>
}
