'use client';
import { Modal } from 'antd';
import { FileTextOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { fmtMoney } from '@/lib/format';

export type DocLine = { description: string; qty: number; rate: number; tax: number; total: number };
export type Doc = {
  type: 'INVOICE' | 'QUOTE';
  docNo: string;
  date: string;
  due?: string;
  customer?: { name?: string; email?: string; phone?: string };
  lines: DocLine[];
  subtotal: number;
  tax: number;
  total: number;
  message?: string;
  memo?: string;
};
export type DocOpts = { showLogo: boolean; showTax: boolean };

function htmlEscape(s: any) { return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

export function buildDocHtml(doc: Doc, opts: DocOpts): string {
  const rows = doc.lines.map((l) => `<tr><td>${htmlEscape(l.description)}</td><td style="text-align:right">${l.qty}</td><td style="text-align:right">${fmtMoney(l.rate)}</td>${opts.showTax ? `<td style="text-align:right">${fmtMoney(l.tax)}</td>` : ''}<td style="text-align:right">${fmtMoney(l.total)}</td></tr>`).join('');
  const head = doc.type === 'INVOICE' ? 'INVOICE' : 'QUOTATION';
  return `<!doctype html><html><head><meta charset="utf-8"><title>${htmlEscape(doc.docNo)}</title><style>
    *{box-sizing:border-box}body{font-family:Inter,system-ui,-apple-system,Segoe UI,Arial,sans-serif;color:#1f2937;margin:0;padding:40px;background:#fff}
    .h{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #003366;padding-bottom:16px}
    .brand{font-size:20px;font-weight:700;color:#003366}.logo{width:34px;height:34px;border-radius:10px;background:#003366;color:#fff;display:inline-flex;align-items:center;justify-content:center;font-weight:700;margin-right:8px}
    .muted{color:#64748b;font-size:12px}.doc{text-align:right}.doc h1{margin:0;font-size:26px;color:#003366}
    .info{display:flex;justify-content:space-between;margin:20px 0}.lbl{color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.03em}
    table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#f7f8fc;text-align:left;padding:10px 8px;font-size:12px;color:#344054}td{padding:10px 8px;border-bottom:1px solid #eef0f6;font-size:13px}
    .tot{width:260px;margin-left:auto;margin-top:16px}.tot div{display:flex;justify-content:space-between;padding:5px 0;font-size:14px}.tot .g{font-weight:700;border-top:1px solid #eef0f6;font-size:16px;color:#003366}
    .msg{margin-top:28px;font-size:13px}.foot{margin-top:40px;border-top:1px solid #eef0f6;padding-top:12px;color:#94a3b8;font-size:11px}
    @media print{body{padding:12mm}}
  </style></head><body>
    <div class="h"><div>${opts.showLogo ? '<span class="logo">N</span>' : ''}<span class="brand">NexusERP</span><div class="muted">Cloud Suite</div></div><div class="doc"><h1>${head}</h1><div class="muted">${htmlEscape(doc.docNo)}</div></div></div>
    <div class="info"><div><div class="lbl">Billed To</div><div style="font-weight:600">${htmlEscape(doc.customer?.name || '—')}</div>${doc.customer?.email ? `<div class="muted">${htmlEscape(doc.customer.email)}</div>` : ''}${doc.customer?.phone ? `<div class="muted">${htmlEscape(doc.customer.phone)}</div>` : ''}</div>
    <div><div class="lbl">Date</div><div>${dayjs(doc.date).format('MM/DD/YYYY')}</div>${doc.due ? `<div class="lbl" style="margin-top:8px">${doc.type === 'INVOICE' ? 'Due' : 'Valid Until'}</div><div>${dayjs(doc.due).format('MM/DD/YYYY')}</div>` : ''}</div></div>
    <table><thead><tr><th>Description</th><th style="text-align:right">Qty</th><th style="text-align:right">Rate</th>${opts.showTax ? '<th style="text-align:right">Tax</th>' : ''}<th style="text-align:right">Amount</th></tr></thead><tbody>${rows}</tbody></table>
    <div class="tot"><div><span>Subtotal</span><span>${fmtMoney(doc.subtotal)}</span></div>${opts.showTax ? `<div><span>Tax</span><span>${fmtMoney(doc.tax)}</span></div>` : ''}<div class="g"><span>Total</span><span>${fmtMoney(doc.total)}</span></div></div>
    ${doc.message ? `<div class="msg"><div class="lbl">${doc.type === 'INVOICE' ? 'Message on Invoice' : 'Message'}</div><div>${htmlEscape(doc.message)}</div></div>` : ''}
    ${doc.memo ? `<div class="msg"><div class="lbl">Statement Memo</div><div>${htmlEscape(doc.memo)}</div></div>` : ''}
    <div class="foot">Generated by NexusERP · ${dayjs().format('YYYY-MM-DD HH:mm')}</div>
  </body></html>`;
}

export function printDoc(doc: Doc, opts: DocOpts) {
  const html = buildDocHtml(doc, opts);
  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) { window.print(); return; }
  w.document.open(); w.document.write(html); w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 300);
}

export function PreviewModal({ open, onClose, doc, opts }: { open: boolean; onClose: () => void; doc: Doc | null; opts: DocOpts }) {
  return (
    <Modal open={open} onCancel={onClose} footer={null} width={820} title={<span className="flex items-center gap-2"><FileTextOutlined style={{ color: '#003366' }} /> Document Preview</span>}>
      {doc ? (
        <div className="border border-[#eef0f6] rounded-xl p-6 bg-white text-slate-800" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
          <div className="flex justify-between items-start border-b-2 border-[#003366] pb-3">
            <div><span className="inline-flex w-7 h-7 rounded-lg bg-[#003366] text-white items-center justify-center font-bold mr-2">N</span><span className="text-[18px] font-bold text-[#003366]">NexusERP</span></div>
            <div className="text-right"><div className="text-[22px] font-bold text-[#003366]">{doc.type}</div><div className="text-[12px] text-[#64748b]">{doc.docNo}</div></div>
          </div>
          <div className="flex justify-between mt-4">
            <div><div className="text-[11px] uppercase tracking-wide text-[#64748b]">Billed To</div><div className="font-semibold">{doc.customer?.name || '—'}</div>{doc.customer?.email && <div className="text-[12px] text-[#64748b]">{doc.customer.email}</div>}</div>
            <div className="text-right"><div className="text-[11px] uppercase tracking-wide text-[#64748b]">Date</div><div>{dayjs(doc.date).format('MM/DD/YYYY')}</div></div>
          </div>
          <table className="w-full border-collapse mt-4"><thead><tr className="bg-[#f7f8fc] text-[12px] text-[#344054]"><th className="text-left p-2">Description</th><th className="text-right p-2">Qty</th><th className="text-right p-2">Rate</th>{opts.showTax && <th className="text-right p-2">Tax</th>}<th className="text-right p-2">Amount</th></tr></thead><tbody>{doc.lines.map((l, i) => (<tr key={i} className="border-b border-[#eef0f6] text-[13px]"><td className="p-2">{l.description}</td><td className="text-right p-2">{l.qty}</td><td className="text-right p-2">{fmtMoney(l.rate)}</td>{opts.showTax && <td className="text-right p-2">{fmtMoney(l.tax)}</td>}<td className="text-right p-2">{fmtMoney(l.total)}</td></tr>))}</tbody></table>
          <div className="ml-auto w-[260px] mt-4"><div className="flex justify-between py-1 text-[14px]"><span>Subtotal</span><span>{fmtMoney(doc.subtotal)}</span></div>{opts.showTax && <div className="flex justify-between py-1 text-[14px]"><span>Tax</span><span>{fmtMoney(doc.tax)}</span></div>}<div className="flex justify-between py-2 font-bold text-[16px] text-[#003366] border-t border-[#eef0f6]"><span>Total</span><span>{fmtMoney(doc.total)}</span></div></div>
          {doc.message && <div className="mt-5 text-[13px]"><div className="text-[11px] uppercase tracking-wide text-[#64748b]">Message</div><div>{doc.message}</div></div>}
          {doc.memo && <div className="mt-3 text-[13px]"><div className="text-[11px] uppercase tracking-wide text-[#64748b]">Statement Memo</div><div>{doc.memo}</div></div>}
        </div>
      ) : null}
    </Modal>
  );
}

